---

- name: checkout repo
  git:
    repo: 'https://github.com/netbootxyz/{{ repo_name }}.git'
    dest: "/opt/builders/{{ repo_name }}"
    version: master

- name: get all branch names
  shell: "git branch -r | grep -v master | awk -F '/' {'print $2'}"
  register: "repo_branches"
  args:
    chdir: "/opt/builders/{{ repo_name }}"

- include_tasks: generate_workflows.yml
  with_items:
  - "{{ repo_branches.stdout_lines }}"
  loop_control:
    loop_var: branch_name

- name: checkout master
  command: "git checkout master"
  args:
    chdir: "/opt/builders/{{ repo_name }}"
  ignore_errors: true

- name: ensure workflow directory is created
  file:
    path: "/opt/builders/{{ repo_name }}/.github/workflows/"
    state: directory

- name: copy workflows to master
  synchronize:
    src: "/opt/builders/{{ repo_name }}_master/.github/workflows/"
    dest: "/opt/builders/{{ repo_name }}/.github/workflows/"
    delete: yes

- name: add changes
  command: "git add ."
  args:
    chdir: "/opt/builders/{{ repo_name }}"
  ignore_errors: true

- name: commit changes
  command: "git commit -m 'Updating workflow automation'"
  args:
    chdir: "/opt/builders/{{ repo_name }}"
  ignore_errors: true

- name: push changes
  command: "git push https://netboot-ci:{{ CI_USER_TOKEN }}@github.com/netbootxyz/{{ repo_name }} master"
  args:
    chdir: "/opt/builders/{{ repo_name }}"
  ignore_errors: true
