---

- name: add changes
  shell: |
    git config --global user.name netboot-ci
    git config --global user.email netboot-ci@netboot.xyz

- name: checkout branch
  command: "git checkout {{ branch_name }}"
  args:
    chdir: "/opt/builders/{{ repo_name }}"
  ignore_errors: true

- name: check if github workflows exists
  stat:
    path: /opt/builders/{{ repo_name }}/.github/workflows/{{ branch_name }}.yml
  register: workflows_exists

- name: ensure workflow directory is created
  file:
    path: "/opt/builders/{{ repo_name }}/.github/workflows/"
    state: directory

- name: generate workflow
  template:
    src: '{{ repo_name }}.yml.j2'
    dest: "/opt/builders/{{ repo_name }}/.github/workflows/{{ branch_name }}.yml"
    force: true

- name: add changes
  command: "git add ."
  args:
    chdir: "/opt/builders/{{ repo_name }}"
  ignore_errors: true

- name: commit changes
  command: "git commit -m 'Updating workflow automation'"
  args:
    chdir: "/opt/builders/{{ repo_name }}"
  ignore_errors: true

- name: push changes
  command: "git push https://netboot-ci:{{ CI_USER_TOKEN }}@github.com/netbootxyz/{{ repo_name }} {{ branch_name }}"
  args:
    chdir: "/opt/builders/{{ repo_name }}"
  ignore_errors: true