name: Update pipeline-status

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
    - name: Run a multi-line script
      env:
        CI_TOKEN: ${{ secrets.CI_TOKEN }}
      run: |
        git config --global user.name netboot-ci
        git config --global user.email netboot-ci@netboot.xyz
        ansible-playbook -i inventory site.yml
