name: Run pipeline generator

on:
  workflow_dispatch:
  schedule:
    - '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      env:
        CI_TOKEN: ${{ secrets.CI_TOKEN }}
      run: |
        git config --global user.name netboot-ci
        git config --global user.email netboot-ci@netboot.xyz
        ansible-playbook -i inventory site.yml
