name: Run pipeline generator

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - name: Run a multi-line script
      env:
        CI_TOKEN: ${{ secrets.CI_TOKEN }}
      run: |
        git config --global user.name netboot-ci
        git config --global user.email netboot-ci@netboot.xyz
        ansible-playbook -i inventory site.yml
